### PR TITLE
Add 'Clear' button

### PR DESCRIPTION
**Pull request by ynoorcsu**
Add clear button and its related code update.

### CODE REVIEW

**Comment by ynoorcsu** [comment]
@bravo90503: Code review please. Once done, please comment 'CRC' and change the label to Code Review Complete (CRC). If you have any question, please just leave a comment.

**Review by bravo90503 — COMMENTED** [review]
looks good.. ok i think i was able to review this without committing..

**Review by bravo90503 — COMMENTED** [review]
CRC

**Comment by ynoorcsu** [comment]
Merged to 'Master'.

**Pull request merged**
