### PR TITLE
Hide elements and code cleanup

### PR DESCRIPTION
**Pull request by ynoorcsu**
@bravo90503 @abarnasankar: CR Please.

### CODE REVIEW

**Review by bravo90503 — COMMENTED** [review]
cleanup looks good.
reset to clear...
insertionsort to applysort...

**Review by abarnasankar — COMMENTED** [review]
Code Changes for the bug https://snatarajan1.myjetbrains.com/youtrack/issue/CPSC544HW1-54
is reviewed.

**Comment by abarnasankar** [comment]
Code changes looks perfect !

**Review by abarnasankar — COMMENTED** [review]
Code Changes looks perfect !

**Pull request merged**
